### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by ch3pjw**
Trying to get Travis to build our Haskell :-)

### CODE REVIEW

**Comment by ch3pjw** [comment]
This is really irritating. It passes locally, even when I try to run it in an `ubuntu:trusty` Docker container to emulate Travis' build environment.

**Comment by foolswood** [comment]
The output might be a bit better, but it seems to have reduced the raciness.
I think actually we need to persuade it not to try and update its output somehow since that's causing it to be really hard to read.

**Comment by ch3pjw** [comment]
The `--no-terminal` option _should_ have suppressed any updating - perhaps there's a bug? Reliable is good for now, though it's weird that it should cause timing issues unless we're getting a port collision or something?

**Comment by foolswood** [comment]
The --no-terminal applies to stack, not to some of the underlying bits, like quickcheck. I think it's more that theoretically we have many cores, but they're heavily contested so it makes the timing issues really bad.

**Comment by ch3pjw** [comment]
Given that you're happy, I'm happy for now. We can revist the number of threads later if needs be.

**Pull request merged**
